spring:
  datasource:
    url: ${SPRING_DATASOURCE_URI}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASS}
    hikari:
      max-lifetime: ${HIKARI_MAX_LIFETIME:600000}
      connectionTimeout: ${HIKARI_CONNECTION_TIMEOUT:5000}
      maximumPoolSize: ${HIKARI_MAX_POOL_SIZE:50}
      minimumIdle: ${HIKARI_MIN_IDLE:5}
      idleTimeout: ${HIKARI_IDLE_TIMEOUT:30000}
      leak-detection-threshold: ${HIKARI_LEAK_DETECTION_THRESHOLD:120000}
      test-while-idle: ${HIKARI_TEST_WHILE_IDLE:true}
      test-on-borrow: ${HIKARI_TEST_ON_BORROW:true}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.validation.mode: none
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO
      apache: INFO
