spring:
  datasource:
    url: ${SPRING_DATASOURCE_URI}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASS}
    hikari:
      max-lifetime: ${HIKARI_MAX_LIFETIME:600000}
      connectionTimeout: ${HIKARI_CONNECTION_TIMEOUT:5000}
      maximumPoolSize: ${HIKARI_MAX_POOL_SIZE:50}
      minimumIdle: ${HIKARI_MIN_IDLE:5}
      idleTimeout: ${HIKARI_IDLE_TIMEOUT:30000}
      leak-detection-threshold: ${HIKARI_LEAK_DETECTION_THRESHOLD:120000}
      test-while-idle: ${HIKARI_TEST_WHILE_IDLE:true}
      test-on-borrow: ${HIKARI_TEST_ON_BORROW:true}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.validation.mode: none
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

  #email setting
  mail:
    host: ${EMAIL_SERVER_HOST}
    port: ${EMAIL_SERVER_PORT}
    username: ${EMAIL_SERVER_USERNAME}
    password: ${EMAIL_SERVER_PASSWORD}

    # Other properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          # TLS , port 587
          starttls:
            enable: true
logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
      apache: INFO

