spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
      apache: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
