# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  dice-app:
    image: diceapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:mysql://candidatemanagement-mysql:3306/candidatemanagement?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    ports:
      - 127.0.0.1:8080:8080
